service: my-express-application

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

plugins:
  - serverless-offline

functions:
  app:
    # handler: express-graphql.handler
    handler: graphql-http.handler
    events:
      - httpApi: "*"
